Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 17, in <module>
    """Fine-tuning models for NER and POS tagging."""
KeyboardInterrupt
Command exited with non-zero status 1
0.02user 0.00system 0:00.03elapsed 100%CPU (0avgtext+0avgdata 12520maxresident)k
0inputs+8outputs (0major+1871minor)pagefaults 0swaps
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 466, in _validate_bytecode_header
KeyboardInterrupt
Command terminated by signal 6
0.01user 0.00system 0:00.15elapsed 11%CPU (0avgtext+0avgdata 7608maxresident)k
0inputs+0outputs (0major+657minor)pagefaults 0swaps
Command terminated by signal 2
0.00user 0.00system 0:00.00elapsed 87%CPU (0avgtext+0avgdata 6056maxresident)k
0inputs+0outputs (0major+439minor)pagefaults 0swaps
Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 28, in <module>
    import json
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap>", line 556, in _init_module_attrs
  File "<frozen importlib._bootstrap>", line 409, in cached
  File "<frozen importlib._bootstrap_external>", line 364, in _get_cached
  File "<frozen importlib._bootstrap_external>", line 300, in cache_from_source
KeyboardInterrupt
Command terminated by signal 2
0.06user 0.00system 0:00.07elapsed 97%CPU (0avgtext+0avgdata 15584maxresident)k
0inputs+8outputs (0major+2598minor)pagefaults 0swaps
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/compat/py3k.py", line 21, in <module>
    from pathlib import Path, PurePath
  File "/usr/lib/python3.6/pathlib.py", line 14, in <module>
    from urllib.parse import quote_from_bytes as urlquote_from_bytes
  File "/usr/lib/python3.6/urllib/parse.py", line 239, in <module>
    'SplitResult', 'scheme netloc path query fragment')
  File "/usr/lib/python3.6/collections/__init__.py", line 429, in namedtuple
    exec(class_definition, namespace)
  File "<string>", line 1, in <module>
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/overrides.py", line 9, in <module>
    from numpy.compat._inspect import getargspec
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/compat/__init__.py", line 12, in <module>
    from . import py3k
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in __exit__
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 30, in <module>
    import numpy as np
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
KeyboardInterrupt
Command exited with non-zero status 1
0.76user 1.06system 0:00.11elapsed 1608%CPU (0avgtext+0avgdata 20300maxresident)k
0inputs+8outputs (0major+3092minor)pagefaults 0swaps
Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 30, in <module>
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/__init__.py", line 72, in <module>
    from . import numeric
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/numeric.py", line 23, in <module>
    from . import shape_base
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/shape_base.py", line 13, in <module>
    from . import fromnumeric as _from_nx
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2419, in <module>
    def cumsum(a, axis=None, dtype=None, out=None):
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/numpy/core/overrides.py", line 181, in decorator
    source, filename='<__array_function__ internals>', mode='exec')
KeyboardInterrupt
Command exited with non-zero status 1
1.33user 1.89system 0:00.12elapsed 2559%CPU (0avgtext+0avgdata 21576maxresident)k
0inputs+0outputs (0major+3390minor)pagefaults 0swaps
