Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 17, in <module>
    """Fine-tuning models for NER and POS tagging."""
KeyboardInterrupt
Command exited with non-zero status 1
0.03user 0.00system 0:00.03elapsed 97%CPU (0avgtext+0avgdata 12532maxresident)k
0inputs+8outputs (0major+1873minor)pagefaults 0swaps
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "/usr/lib/python3.6/_bootlocale.py", line 8, in <module>
    import _locale
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 321, in __exit__
KeyboardInterrupt
Command terminated by signal 6
0.01user 0.00system 0:00.14elapsed 12%CPU (0avgtext+0avgdata 7620maxresident)k
0inputs+0outputs (0major+667minor)pagefaults 0swaps
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 570, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 553, in main
    known_paths = venv(known_paths)
  File "/usr/lib/python3.6/site.py", line 490, in venv
    addsitepackages(known_paths, [sys.prefix])
  File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.6/site.py", line 213, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.6/site.py", line 174, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
KeyboardInterrupt
Command exited with non-zero status 1
0.01user 0.01system 0:00.02elapsed 100%CPU (0avgtext+0avgdata 8596maxresident)k
0inputs+0outputs (0major+862minor)pagefaults 0swaps
Command terminated by signal 2
0.00user 0.00system 0:00.00elapsed 100%CPU (0avgtext+0avgdata 4908maxresident)k
0inputs+0outputs (0major+239minor)pagefaults 0swaps
Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 23, in <module>
    import logging
  File "/usr/lib/python3.6/logging/__init__.py", line 41, in <module>
    import threading
  File "/usr/lib/python3.6/threading.py", line 487, in <module>
    class Event:
  File "/usr/lib/python3.6/threading.py", line 498, in Event
    def __init__(self):
KeyboardInterrupt
Command exited with non-zero status 1
0.05user 0.00system 0:00.05elapsed 100%CPU (0avgtext+0avgdata 12504maxresident)k
64inputs+0outputs (0major+2070minor)pagefaults 0swaps
Command terminated by signal 2
0.00user 0.00system 0:00.00elapsed 87%CPU (0avgtext+0avgdata 6068maxresident)k
0inputs+0outputs (0major+439minor)pagefaults 0swaps
